### ISSUE TITLE
Tags / Relases

### ISSUE THREAD

**Issue by baukezwaan** [lekoala/silverstripe-form-elements#2]
Hi @lekoala 

Really like your work in this module!
Would it be possible to use some tags / releases in this repo? So we can keep using it in ss4 projects for now.

Thnx!

**Comment by lekoala** [comment]
thanks ! yes sure i will tag the ss4 release and try to be a bit more organized :-) it was mostly for my self use so far

**Comment by lekoala** [comment]
tag 0.1 should work fine on ss4

**Comment by baukezwaan** [comment]
Thanks, works perfect!
